### ISSUE TITLE
version android

### ISSUE THREAD

**Issue by wilfried18** [Atraci/Atraci-Android#1]
When will you have it apk (version alpha, beta etc) to test

**Comment by avihaymenahem** [comment]
we are trying to build it right now, but it costs us a lot of money, need to raise some to work on this too :(
for now its 12% complete

**Comment by wilfried18** [comment]
Ok, I will present your software (atracie) on my blog in French and I would do the same with the android release. 
Thank you for your work

**Comment by Blackburn29** [comment]
APK can be found in /bin

closed.

**Comment by Blackburn29** [comment]
just be aware that APK is bleeding edge and will likely contain bugs and unfinished features. it is nowhere near release yet
