### ISSUE TITLE
Add a .apk file

### ISSUE THREAD

**Issue by mimi89999** [Atraci/Atraci-Android#11]
Could you add a .apk file to download.

**Comment by Blackburn29** [comment]
Yes, one second.

**Comment by Blackburn29** [comment]
https://github.com/Atraci/Atraci-Android/tree/dev/apk

Latest APK can be found at the above URL.

**Comment by cinzianicoletti** [comment]
I don't know what is the problem, but it doesn't work (android and Windows 8). There are problem with the server?
